### ISSUE TITLE
Create needed directories

### ISSUE THREAD

**Issue by Tundra-bit** [duracell80/MoodeRadio-Get#6]
Hey good work!

Heads up, I received these errors at the end of the installation:

```
cp: cannot create regular file '/var/www/images/radio-logos/': Not a directory
cp: cannot create regular file '/var/www/images/radio-logos/thumbs': No such file or directory
```

Solved with:

`mkdir -p /var/www/images/radio-logos/thumbs`

```
DirRadiologos="/var/www/images/radio-logos/"
DirThumbs="/var/www/images/radio-logos/thumbs"

if [[ ! -e ${DirRadiologos} ]] && [[ ! -e ${DirThumbs} ]]; then
    mkdir -p ${DirThumbs}
else
    echo "${DirRadiologos} already exists " 1>&2
fi
```

Thanks for the project, really enjoying this.

**Comment by duracell80** [comment]
Awesome! Thank you for the code.

**Comment by Tundra-bit** [comment]
The more I dig into your work, the more i'm impressed.

Having a little issue with Icons. 
[https://imgur.com/a/xRPl3Ck](https://imgur.com/a/xRPl3Ck)

Would you know how I can re-create the icons in bulk for radio stations?

Thanks

**Comment by duracell80** [comment]
Thank you, I need to work on it a bit more but it's mostly there.

I had created the example ones in Photoshop as square images. Not sure but there could be a path/directory or permissions issue there maybe.

Also images in Moode are subject to caching.

**Comment by duracell80** [comment]
@Tundra-bit I looked at this over the weekend and updated some paths. Thanks for your report.

Looks like the web directories had a little move around, let me know if this resolves for you. I would go ahead and delete the git repo from the pi and reclone it. I tried it on the latest version of moode and got the images restored.
